server:
    host: localhost
    port: 1337

log:
    request: true
    response: true

mongo:
    - name    : primary
      host    : host
      port    : port
      db      : db
      user    : user
      password: pass